//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotes
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public int Produto { get; set; }
        public Nullable<System.DateTime> Validade { get; set; }
        public float Quantidade { get; set; }
        public decimal PrecoCusto { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Produtos Produtos { get; set; }
    }
}
